name: Deploy Application Docker Image to EC2 instance

on:
  push:
    branches: [main]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .  
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to EC2 via Native AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-0d22e4f65385435b0" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws ecr get-login-password --region '"${{ secrets.AWS_DEFAULT_REGION }}"' | docker login --username AWS --password-stdin '"${{ secrets.AWS_ACCESS_KEY_ID }}"'.dkr.ecr.'"${{ secrets.AWS_DEFAULT_REGION }}"'.amazonaws.com",
              "docker stop engineering-copilot || true",
              "docker rm engineering-copilot || true",
              "docker pull '"${{ secrets.AWS_ACCESS_KEY_ID }}"'.dkr.ecr.'"${{ secrets.AWS_DEFAULT_REGION }}"'.amazonaws.com/'"${{ secrets.ECR_REPO }}"':latest",
              "docker run -d --name engineering-copilot -e JWT_SECRET_KEY=\"'"${{ secrets.JWT_SECRET_KEY }}"'\" -e AUTH_USERNAME=\"'"${{ secrets.AUTH_USERNAME }}"'\" -e AUTH_PASSWORD=\"'"${{ secrets.AUTH_PASSWORD }}"'\" -e PINECONE_API_KEY=\"'"${{ secrets.PINECONE_API_KEY }}"'\" -e OPENAI_API_KEY=\"'"${{ secrets.OPENAI_API_KEY }}"'\" -p 8080:8080 '"${{ secrets.AWS_ACCESS_KEY_ID }}"'.dkr.ecr.'"${{ secrets.AWS_DEFAULT_REGION }}"'.amazonaws.com/'"${{ secrets.ECR_REPO }}"':latest"
            ]}'